
version: 2.1
jobs:
  
#   create_and_deploy_front_end:
#     docker:
#       - image: amazon/aws-cli
#     steps:
#       - checkout
#       - run:
#           name: Execute bucket.yml - Create Cloudformation Stack
#           command: |
#             aws cloudformation deploy \
#             --template-file bucket.yml \
#             --stack-name stack-create-bucket-${CIRCLE_WORKFLOW_ID:0:7} \
#             --parameter-overrides MyBucketName="mybucket-${CIRCLE_WORKFLOW_ID:0:7}"
#       - run: aws s3 cp s3://mybucket642862753081/index.html s3://mybucket-${CIRCLE_WORKFLOW_ID:0:7} 

# workflows:
#   Create:
#     jobs:
#       - create_and_deploy_front_end

  get_last_deployment_id:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: yum install -y tar gzip
      - run:
          name: Fetch and save the old pipeline ID (bucket name) responsible for the last release.
          command: |
            aws cloudformation \
            list-exports --query "Exports[?Name==\`PipelineID\`].Value" \
            --no-paginate --output text > ~/textfile.txt

      - persist_to_workspace:
          root: ~/
          paths: 
            - textfile.txt 

workflows:
    Create:
      jobs:
        - get_last_deployment_id